### Login yap, token al
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "ahmet@example.com",
  "password": "guclu-sifre-123"
}

### Token'sız istek - artık 401 vermeli
GET http://localhost:8080/api/customers

### Token'lı istek - buraya bir önceki isteğin token'ını yapıştıracaksın
GET http://localhost:8080/api/customers
Authorization: Bearer BURAYA_TOKEN_YAPISTIR


### Token'lı istek
GET http://localhost:8080/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaG1ldEBleGFtcGxlLmNvbSIsInVzZXJJZCI6MSwiY3VzdG9tZXJJZCI6MSwiaWF0IjoxNzg1NDE2ODAxLCJleHAiOjE3ODU1MDMyMDF9.p-WvtAqo-6I_HUH3qvJrMroDju8yJ-hh1PxpYvZAHCg